theme: jekyll-theme-architect
title: openTAL
description:  open test adaption layer
show_downloads:  false
baseurl:  "/"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
